name: Codecov

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install -g npm

      - name: Install Nx
        run: npm install -g nx

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Clean all
        run: npm run clean

      - name: Setup repo
        run: npm run setup

      - name: Build repo
        run: npm run build

      - name: Build repo
        run: cd packages/formesome && npm run test:coverage

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
